apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kumarbusiness-tls-cert
  namespace: ecommerce
spec:
  secretName: kumarbusiness-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dev.kumarbusiness.online
  dnsNames:
    - dev.kumarbusiness.online
