apiVersion: v1
kind: ConfigMap
metadata:
  name: easyshop-config
  namespace: ecommerce
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/easyshop"
  NEXT_PUBLIC_API_URL: "http://kumarbusiness.online/api"
  NEXTAUTH_URL: "http://kumarbusiness.online"
