apiVersion: v1
kind: Secret
metadata:
  name: easyshop-secrets
  namespace: ecommerce
type: Opaque
stringData:
  NEXTAUTH_SECRET: "/Uc10a/9lpC58MU28n0k+Du++ctzYh4C/XX7uoQYgvk="
  JWT_SECRET: "2cf02cb7db689c5584b79bfa3a98ddecf00d49b871d16346cf1ede434f6befff"